In [1]:
#Numpy
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
a=np.array([1,2,3,'A'])
print(a)

['1' '2' '3' 'A']


In [7]:
a=np.array([1,2,3,12.45])
print(a)

[ 1.    2.    3.   12.45]


In [16]:
a=np.array([[1,2],[12, 45]])
print(a)

(2, 2)


In [20]:
a=np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [26]:
#dtype parameter
a=np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [2]:
a=np.array([[2,3,5 ], [9,11,7], [3,2,7]])
print(a)
        

[[ 2  3  5]
 [ 9 11  7]
 [ 3  2  7]]


In [4]:
#Addition of two matrix
x=np.array([[2,3,4],[2,2,4], [3,4,6]])
print(x)
print()

y=np.array([[1,4,6],[2,4,6], [3,5,8]])
print(y)
print()
z=x+y
print(z)

[[2 3 4]
 [2 2 4]
 [3 4 6]]

[[1 4 6]
 [2 4 6]
 [3 5 8]]

[[ 3  7 10]
 [ 4  6 10]
 [ 6  9 14]]


In [10]:
#Shape function
a=np.array([[2,3,4],[2,2,4], [3,4,6]])
print(a.shape)

(3, 3)


In [9]:
x=np.array([[2,3,4],[3,4,6]])
x.shape=(3,2)
print(x)

[[2 3]
 [4 3]
 [4 6]]


In [14]:
#Reshape function
x=np.array([[2,3,4],[3,4,6]])
print(x)
print()
y=x.reshape(3,2)
print(y)

[[2 3 4]
 [3 4 6]]

[[2 3]
 [4 3]
 [4 6]]


In [15]:
#numpy.zeros
x=np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [16]:
#numpy.ones
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [21]:
x=np.ones([1,3,4,3], dtype=int)
print(x)

[[[[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]
   [1 1 1]]]]


In [2]:
x=np.array([[2,3,4,5,6],[2,2,4,6,7], [3,4,6,7,6], [3,5,7,8,6], [5,6,7,8,7]])
print(x)

[[2 3 4 5 6]
 [2 2 4 6 7]
 [3 4 6 7 6]
 [3 5 7 8 6]
 [5 6 7 8 7]]


In [5]:
print(np.diag(x))

[2 2 6 8 7]


In [6]:
ls=[12,34,55,66]
print(np.diag(ls))

[[12  0  0  0]
 [ 0 34  0  0]
 [ 0  0 55  0]
 [ 0  0  0 66]]


In [9]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Arange
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [1]:
#Transpose Matrix
import numpy as np
matrix1=np.array([[1,3],[5,7]])
print(matrix1)
print()
#get transpose of matrix
result=np.transpose(matrix1)
print(result)

[[1 3]
 [5 7]]

[[1 5]
 [3 7]]


In [2]:
#Create Two Matrices
matrix1=np.array([[1,3],
                  [5,7]])
matrix2=np.array([[2,6],
                  [4,8]])
result=np.dot(matrix1,matrix2)
print("matrix1*matrix2: \n",result)

matrix1*matrix2: 
 [[14 30]
 [38 86]]


In [10]:
#Accessing 2d
x=np.array([[2,3,4,6,7],[2,2,6,8,4], [3,7,8,4,6],[1,2,8,8,4], [3,7,5,4,9]])


print(x[1:4,0:3])

[[2 2 6]
 [3 7 8]
 [1 2 8]]


In [12]:
import time
import sys
sys.getsizeof(1000)


28

In [13]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [14]:
sys.getsizeof(100)

28

In [16]:
a=np.arange(200000)
a.itemsize

4

In [17]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


In [18]:
a1=range(1000000)
b1=range(1000000)
start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken:", (time.time()-start)*1000)

time taken: 200.78420639038086


In [19]:
a=[1,2]
b=[4,7]
list(zip(a,b))

[(1, 4), (2, 7)]

In [21]:
a2=np.arange(100000)
b2=np.arange(100000)
start=time.time()
c2=a2+b2
print("Time taken by array:",(time.time()-start)*1000)

Time taken by array: 2.7875900268554688


In [22]:
n1=np.arange(100)
n2=np.arange(100)
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [23]:
#Numpy.linspace
x=np.linspace(10,20,5)
print(x)


[10.  12.5 15.  17.5 20. ]


In [25]:
#Endpoint=false
x=np.linspace(10,20,5,endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [26]:
#Find retstep value
x=np.linspace(1,2,5,retstep=True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [27]:
#Numpy.hstack() Function
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
np.hstack((x,y))

[3 5 7]

[5 7 9]



array([3, 5, 7, 5, 7, 9])

In [28]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
np.hstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]



array([[3, 5],
       [5, 7],
       [7, 9]])

In [29]:
x=np.array((3,5,7))
print(x)
print()
y=np.array((5,7,9))
print(y)
print()
np.vstack((x,y))

[3 5 7]

[5 7 9]



array([[3, 5, 7],
       [5, 7, 9]])

In [30]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[7],[9]])
print(y)
print()
np.vstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [7]
 [9]]



array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

In [31]:
#Condition
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [32]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
a[a==5]

array([5])

In [38]:
a[a<5]

array([1, 2, 3, 4])

In [41]:
a[a%2!=0]=0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [42]:
a=10
b=20
a+b

30

In [9]:
#Random Number Integer
import numpy as np
random_number=np.random.randint(0,10)
random_number


5

In [14]:
from numpy import random
random_number=random.randint(10,20)
random_number

14

In [19]:
random_number=np.random.rand()
random_number

0.950221253371869

In [24]:
integer_array=np.random.randint(0,10,5)
print("1D random integer array:\n",integer_array)

1D random integer array:
 [0 2 5 2 0]


In [28]:
float_array=np.random.rand(5)
print("1D random float array:\n",float_array)

1D random float array:
 [2.39814697e-01 1.97815001e-01 3.76545399e-05 6.24411768e-01
 2.18719713e-01]


In [27]:
#Generate 2D array
result=np.random.randint(0,10,(3,4))
print("2D random integer array:\n",result)

2D random integer array:
 [[1 3 1 8]
 [5 4 6 4]
 [4 9 8 5]]


In [32]:
np.random.randn(5,5)

array([[-0.41397905, -0.24970487,  0.0563931 ,  0.65305199, -0.41403464],
       [-1.09903612, -2.05463354,  0.60700508,  0.3035904 ,  1.22766003],
       [ 0.34285004, -0.33369633, -0.22166818,  2.70760787,  0.20008296],
       [-0.30170346, -1.42446677, -0.03496138, -0.94089983, -0.23635673],
       [ 1.39804255, -0.89026711, -0.166848  , -0.25930739,  0.49616755]])

In [37]:
np.random.randint(100,300,20).reshape(4,5)

array([[127, 145, 244, 183, 142],
       [284, 146, 171, 231, 155],
       [293, 272, 220, 102, 197],
       [200, 180, 245, 290, 213]])

In [67]:
from numpy.random import randint as ri
np.random.seed(675)
m=ri(1,100,(5,6))
print(m)

array([[42, 81,  3, 10, 39, 37],
       [ 3, 57,  4, 90, 28, 41],
       [17, 61, 53, 98, 53, 16],
       [85, 95, 61, 83, 63, 11],
       [82, 82, 55, 34, 13, 99]])

In [68]:
np.random.seed(675)
m=ri(1,100,(5,5))
print(m)

[[42 81  3 10 39]
 [37  3 57  4 90]
 [28 41 17 61 53]
 [98 53 16 85 95]
 [61 83 63 11 82]]


In [69]:
np.sort(m)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [70]:
np.sort(m,axis=0)

array([[28,  3,  3,  4, 39],
       [37, 41, 16, 10, 53],
       [42, 53, 17, 11, 82],
       [61, 81, 57, 61, 90],
       [98, 83, 63, 85, 95]])

In [76]:
a=ri(1,100,30)
a

array([59, 31, 20, 86, 14, 98, 53, 80, 79, 57, 72, 52, 44, 47, 22, 78, 67,
       93, 33, 39, 48, 17, 52, 81, 26, 56, 54, 21, 26, 92])

In [77]:
a.max()

98

In [78]:
a.min()

14

In [80]:
a.argmax() #Return index of maximun number

5

In [81]:
ls=[121,23,34,145,56,18]
a=np.array(ls)
a.argsort() #it retrun the soft index

array([5, 1, 2, 4, 0, 3], dtype=int64)

In [82]:
a=ri(1,100,30)
b=a.reshape(6,5)
b

array([[89, 87, 29, 94, 53],
       [61, 27, 63, 71,  5],
       [96, 73, 29, 11, 72],
       [41, 27, 89, 21, 95],
       [22,  7, 68, 43, 84],
       [13, 61, 72, 85, 56]])

In [83]:
b.max(axis=0) #Max value of every column

array([96, 87, 89, 94, 95])

In [84]:
b.max(axis=1) #Max value of every row

array([94, 71, 96, 95, 84, 85])

In [85]:
b.argmax(axis=1)

array([3, 3, 0, 4, 4, 3], dtype=int64)

In [86]:
a=np.array([1,2,3,4,5,2])
a

array([1, 2, 3, 4, 5, 2])

In [87]:
a.ndim

1

In [88]:
a.shape

(6,)

In [89]:
np.where(a==2)

(array([1, 5], dtype=int64),)

In [90]:
np.where(a==3)

(array([2], dtype=int64),)

In [91]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [92]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [100]:
np.where(b>5)

(array([5], dtype=int64),)

In [95]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
#Even Numbers
np.where(x%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [97]:
#odd Numbers
np.where(x%2!=0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [98]:
#Seachsoted
x=np.array([1,2,3,4,10,11,15])
x

array([ 1,  2,  3,  4, 10, 11, 15])

In [99]:
np.searchsorted(x,8)

4